version: "3.7"
services:
    go-server:
        container_name: go-server
        build: ./go/server
        networks:
            - demo
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-server-go
            - LIGHTSTEP_SERVICE_VERSION=5
    go-client:
        container_name: go-client
        build: ./go/client
        networks:
            - demo
        depends_on:
            - go-server
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-client-go
            - LIGHTSTEP_SERVICE_VERSION=1.2.7
            - TARGET_URL=http://go-server:8081
    py-client:
        container_name: py-client
        build: ./python/client
        networks:
            - demo
        depends_on:
            - py-server
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-client-py
            - LIGHTSTEP_SERVICE_VERSION=1.2.1
            - TARGET_URL=http://py-server:5000
    py-server:
        container_name: py-server
        build: ./python/server
        networks:
            - demo
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-server-py
            - LIGHTSTEP_SERVICE_VERSION=0.2.2
    js-server:
        container_name: js-server
        build: ./js/server
        networks:
            - demo
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=ls-trace-js-server
    js-client:
        container_name: js-client
        build: ./js/client
        networks:
            - demo
        depends_on:
            - js-server
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=ls-trace-js-client
            - TARGET_URL=http://js-server:8080/ping
    java-server:
        container_name: java-server
        build: ./java/server
        networks:
            - demo
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-server-java
            - LIGHTSTEP_SERVICE_VERSION=4.3.2
    java-client:
        container_name: java-client
        build: ./java/client
        networks:
            - demo
        depends_on:
            - java-server
        env_file:
            - .env
        environment:
            - LIGHTSTEP_COMPONENT_NAME=demo-client-java
            - LIGHTSTEP_SERVICE_VERSION=3.2.1
            - TARGET_URL=http://java-server:8083

networks:
    demo:
