receivers:
    opencensus:
      endpoint: "0.0.0.0:55678"
  
exporters:
    prometheus:
        endpoint: "0.0.0.0:8889"

    logging:
        loglevel: debug

    lightstep:
        access_token: <TOKEN HERE>
        satellite_host: "ingest.staging.lightstep.com"
        satellite_port: 443
        service_name: "myService"
        plain_text: false
  
processors:
    batch:
    queued_retry:
  
service:
    pipelines:
      traces:
        receivers: [opencensus]
        exporters: [logging, lightstep]
        processors: [batch]
      metrics:
        receivers: [opencensus]
        exporters: [logging]